stages:
- test
- push

variables:
  DOCKER_PREFIX: registry.gitlab.com/atlantic-crypto/kubevirt
  DOCKER_TAG: ${CI_COMMIT_SHA}
  

test:
  stage: test
  only:
    refs:
    - coreweave
  script:
  - make test

push:
  stage: push
  only:
    refs:
    - coreweave
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push
